### ISSUE TITLE
Приходько: Убрать отображение аналогов во время формирования внутреннего заказа

### ISSUE THREAD

**Issue by movis08** [vgulaev/TAM#16]
Список аналоговых позиций:
http://rghost.ru/7RKMr2dDX ~ 1300

**Comment by movis08** [comment]
https://github.com/vgulaev/TAM/issues/27

**Comment by movis08** [comment]
Это как я понимаю одно и тоже?))

**Comment by vgulaev** [comment]
Да это одно и тоже

**Comment by movis08** [comment]
Закрыто так как является той же самой задачей, что и задача номер 27
