### ISSUE TITLE
Бутаков: Печатная форма Инвентаризация товаров на складе из УТ в Кортес

### ISSUE THREAD

**Issue by vgulaev** [vgulaev/TAM#23]
Без колонок:  "Цена",  "Сумма", "Сумма по учету"
И с пустыми колонками Кол-во, Кол-во по учету

**Comment by movis08** [comment]
Инвентаризация товаров на складе

**Comment by movis08** [comment]
Сделал. Хотелось бы услышать оценку)
И вообще то вывел иль не то)))))
Что подкорректировать может?

**Comment by vgulaev** [comment]
Добавить подписи ответственных в подвал документа

**Comment by movis08** [comment]
Добавлены подписи
